# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [28]:
import numpy as np

#### 2. Print your NumPy version.

In [29]:
np.__version__

'1.21.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [30]:
# Method 1
a = np.random.random((2,3,5))

In [31]:
# Method 2
lista = []
import random
for i in range(0,30):
    number = random.random()
    lista.append(number)
a = np.array([lista])
a = a.reshape(2,3,5)

In [32]:
# Method 3


#### 4. Print *a*.


In [33]:
print(a)

[[[0.11163188 0.54302455 0.75137019 0.59467455 0.24755544]
  [0.3999937  0.73720833 0.39212863 0.27197056 0.55785178]
  [0.88530095 0.56904184 0.50540244 0.27310575 0.19465787]]

 [[0.54745861 0.50127153 0.9275026  0.12007732 0.22040124]
  [0.17917357 0.58116866 0.66857696 0.77788995 0.29464424]
  [0.25404763 0.6981928  0.27530224 0.01355567 0.97154501]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [34]:
# your code here
b = np.ones(shape=(5,2,3))

#### 6. Print *b*.


In [35]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [36]:
# your code here
print(a.size)
print(b.size)

if a.size == b.size:
    print('Both have the same size')

30
30
Both have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [37]:
# your answer here
ab = a+b
'''
Both arrays cannot be summed because the shapes are different,even though sizes are the same
'''

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [38]:
# your code here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [39]:
# your code/answer here
d = a + c
'''
This works now because the shape of the arrays are the same
'''

'\nThis works now because the shape of the arrays are the same\n'

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [40]:
# your code/answer here
print(a)
print('----')
print(d)

'''
Explanation: as d has the same values as the b array, and b array was composed by ones, 
the result of the sum is the sum of each element of the array a added to the element in the same position in the array d
that is d is the same array than a but with its elements' value increased in 1
'''

[[[0.11163188 0.54302455 0.75137019 0.59467455 0.24755544]
  [0.3999937  0.73720833 0.39212863 0.27197056 0.55785178]
  [0.88530095 0.56904184 0.50540244 0.27310575 0.19465787]]

 [[0.54745861 0.50127153 0.9275026  0.12007732 0.22040124]
  [0.17917357 0.58116866 0.66857696 0.77788995 0.29464424]
  [0.25404763 0.6981928  0.27530224 0.01355567 0.97154501]]]
----
[[[1.11163188 1.54302455 1.75137019 1.59467455 1.24755544]
  [1.3999937  1.73720833 1.39212863 1.27197056 1.55785178]
  [1.88530095 1.56904184 1.50540244 1.27310575 1.19465787]]

 [[1.54745861 1.50127153 1.9275026  1.12007732 1.22040124]
  [1.17917357 1.58116866 1.66857696 1.77788995 1.29464424]
  [1.25404763 1.6981928  1.27530224 1.01355567 1.97154501]]]


"\nExplanation: as d has the same values as the b array, and b array was composed by ones, \nthe result of the sum is the sum of each element of the array a added to the element in the same position in the array d\nthat is d is the same array than a but with its elements' value increased in 1\n"

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [41]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [42]:
# your code/answer here
a == e

print('same explanation than before, each element of a multiplies each element of c (that is, 1)')

same explanation than before, each element of a multiplies each element of c (that is, 1)


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [43]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [44]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.09284318, 0.55967091, 0.51167989, 0.5187983 , 0.33912685],
        [0.6833244 , 0.76511609, 0.24237002, 0.71672775, 0.27724615],
        [0.83180241, 0.82868259, 0.51268637, 0.02027204, 0.94919565]],

       [[0.06484814, 0.66849966, 0.44674628, 0.48261965, 0.73083974],
        [0.12933094, 0.03471306, 0.53053545, 0.76824099, 0.49227225],
        [0.23663087, 0.0789756 , 0.85339457, 0.58129185, 0.52756132]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [45]:
# your code here
def new_array_3dim(x,y):
    x_max = x.max()
    x_min = x.min()
    x_mean = x.mean()
    
    shape = x.shape
    
    for i in range(shape[0]):
        for j in range(shape[1]):
            for k in range(shape[2]):
                if x_min < x[i,j,k] < x_mean:
                    y[i,j,k]=25
                elif x_mean < x[i,j,k] < x_max:
                    y[i,j,k]=75
                elif x[i,j,k] == x_mean:
                    y[i,j,k]=50
                elif x[i,j,k] == x_min:
                    y[i,j,k]=0
                elif x[i,j,k] == x_max:
                    y[i,j,k]=100


In [46]:
new_array_3dim(d,f)
print(f)

[[[ 25.  75.  75.  75.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.  75.  75.  25.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  75.  25.   0. 100.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [47]:
# your code here
print(d)
print(' ')
print(f)

[[[1.11163188 1.54302455 1.75137019 1.59467455 1.24755544]
  [1.3999937  1.73720833 1.39212863 1.27197056 1.55785178]
  [1.88530095 1.56904184 1.50540244 1.27310575 1.19465787]]

 [[1.54745861 1.50127153 1.9275026  1.12007732 1.22040124]
  [1.17917357 1.58116866 1.66857696 1.77788995 1.29464424]
  [1.25404763 1.6981928  1.27530224 1.01355567 1.97154501]]]
 
[[[ 25.  75.  75.  75.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.  75.  75.  25.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  75.  25.   0. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [67]:
# your code here
def new_array_3dim_letters(x,y):
    x_max = x.max()
    x_min = x.min()
    x_mean = x.mean()
    y = y.astype(str)
    shape = x.shape
    
    for i in range(shape[0]):
        for j in range(shape[1]):
            for k in range(shape[2]):
                if x_min < x[i,j,k] < x_mean:
                    y[i,j,k]='B'
                elif x_mean < x[i,j,k] < x_max:
                    y[i,j,k]='D'
                elif x[i,j,k] == x_mean:
                    y[i,j,k]='C'
                elif x[i,j,k] == x_min:
                    y[i,j,k]='A'
                elif x[i,j,k] == x_max:
                    y[i,j,k]='E'
    return y

In [70]:
new_array_3dim_letters(d,f)

array([[['B', 'D', 'D', 'D', 'B'],
        ['B', 'D', 'B', 'B', 'D'],
        ['D', 'D', 'D', 'B', 'B']],

       [['D', 'D', 'D', 'B', 'B'],
        ['B', 'D', 'D', 'D', 'B'],
        ['B', 'D', 'B', 'A', 'E']]], dtype='<U32')